{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOhlVcC+Q7Bk0Pf2/8yrK2j",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/regitaaajuairianiii-bit/fiskom_tugas5/blob/main/dashboard_fiskom.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# -*- coding: utf-8 -*-\n",
        "\"\"\"\n",
        "Dashboard Analisis Siswa - Tema Pastel\n",
        "\"\"\"\n",
        "\n",
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import statsmodels.api as sm\n",
        "from sklearn.cluster import KMeans\n",
        "from sklearn.preprocessing import StandardScaler\n",
        "import seaborn as sns\n",
        "\n",
        "# ==========================================================\n",
        "# 1️⃣ KONFIGURASI HALAMAN & INJEKSI CSS\n",
        "# ==========================================================\n",
        "st.set_page_config(page_title=\"Dashboard Analisis Siswa\", layout=\"wide\")\n",
        "\n",
        "st.markdown(\"\"\"\n",
        "<style>\n",
        "    /* Latar belakang utama aplikasi (Pastel Peach/Pink) */\n",
        "    .stApp {\n",
        "        background-color: #FFF0F5;\n",
        "    }\n",
        "    /* Warna header dan judul (Pastel Purple) */\n",
        "    h1, h2, h3 {\n",
        "        color: #9B89B3 !important;\n",
        "        font-family: 'Arial', sans-serif;\n",
        "    }\n",
        "    /* Kotak metrik (Custom Card Style) */\n",
        "    div[data-testid=\"metric-container\"] {\n",
        "        background-color: #FFFFFF;\n",
        "        border: 2px solid #FFD1DC;\n",
        "        padding: 15px;\n",
        "        border-radius: 15px;\n",
        "        box-shadow: 2px 2px 10px rgba(0,0,0,0.05);\n",
        "    }\n",
        "    /* Warna teks di dalam metrik */\n",
        "    div[data-testid=\"stMetricValue\"] {\n",
        "        color: #FFB6C1 !important; /* Pastel Pink */\n",
        "    }\n",
        "    div[data-testid=\"stMetricLabel\"] {\n",
        "        color: #87CEFA !important; /* Light Sky Blue */\n",
        "        font-weight: bold;\n",
        "    }\n",
        "</style>\n",
        "\"\"\", unsafe_allow_html=True)\n",
        "\n",
        "st.title(\"🌸 Dashboard Analisis Hasil Simulasi Siswa\")\n",
        "st.markdown(\"**Analisis otomatis untuk data 50 siswa dan 20 soal dengan sentuhan warna pastel yang ceria!** 🎨\")\n",
        "\n",
        "# ==========================================================\n",
        "# 2️⃣ LOAD DATA\n",
        "# ==========================================================\n",
        "file_path = \"data_simulasi_50_siswa_20_soal.xlsx\"\n",
        "\n",
        "try:\n",
        "    df = pd.read_excel(file_path)\n",
        "    indikator = df.apply(pd.to_numeric, errors=\"coerce\")\n",
        "except Exception as e:\n",
        "    st.error(f\"Gagal membaca file: {e}\")\n",
        "    st.info(\"Pastikan file Excel (data_simulasi_50_siswa_20_soal.xlsx) berada di folder yang sama dengan skrip ini.\")\n",
        "    st.stop()\n",
        "\n",
        "# ==========================================================\n",
        "# 3️⃣ KPI KEPUASAN / CAPAIAN (Skala 1-4)\n",
        "# ==========================================================\n",
        "mean_scores = indikator.mean()\n",
        "total_avg = mean_scores.mean()\n",
        "ikm = (total_avg / 4) * 100\n",
        "\n",
        "def kategori_capaian(x):\n",
        "    if x >= 80: return \"🌟 Sangat Baik\"\n",
        "    elif x >= 65: return \"😊 Baik\"\n",
        "    elif x >= 50: return \"😐 Cukup\"\n",
        "    else: return \"😥 Kurang\"\n",
        "\n",
        "col1, col2, col3 = st.columns(3)\n",
        "col1.metric(\"📈 Rata-rata Skor\", f\"{total_avg:.2f}\")\n",
        "col2.metric(\"🏷️ Kategori\", kategori_capaian(ikm))\n",
        "col3.metric(\"👥 Total Responden\", len(df))\n",
        "\n",
        "st.divider()\n",
        "\n",
        "# ==========================================================\n",
        "# 4️⃣ ANALISIS GAP (Target Skor Sempurna = 4)\n",
        "# ==========================================================\n",
        "st.header(\"🎯 Analisis GAP per Soal\")\n",
        "st.caption(\"Gap dihitung dari selisih skor maksimal (4) dengan rata-rata saat ini\")\n",
        "\n",
        "gap_scores = 4 - mean_scores\n",
        "prioritas_soal = gap_scores.idxmax()\n",
        "\n",
        "# Palet warna pastel untuk bar chart\n",
        "pastel_colors = sns.color_palette(\"pastel\", len(gap_scores))\n",
        "\n",
        "fig_gap, ax_gap = plt.subplots(figsize=(12, 5))\n",
        "fig_gap.patch.set_facecolor('#FFF0F5')\n",
        "ax_gap.set_facecolor('#FFF0F5')\n",
        "\n",
        "gap_scores.plot(kind='bar', color=pastel_colors, ax=ax_gap, edgecolor='white')\n",
        "ax_gap.set_ylabel(\"Nilai GAP\", color='#9B89B3', fontweight='bold')\n",
        "ax_gap.set_title(\"GAP per Indikator Soal\", color='#9B89B3', fontweight='bold')\n",
        "ax_gap.tick_params(colors='#9B89B3', rotation=45)\n",
        "\n",
        "ax_gap.spines['top'].set_visible(False)\n",
        "ax_gap.spines['right'].set_visible(False)\n",
        "ax_gap.spines['left'].set_color('#FFD1DC')\n",
        "ax_gap.spines['bottom'].set_color('#FFD1DC')\n",
        "\n",
        "st.pyplot(fig_gap)\n",
        "\n",
        "st.warning(f\"📌 **Prioritas Perbaikan:** Fokus pada **{prioritas_soal}** karena memiliki GAP terbesar ({gap_scores.max():.2f}).\")\n",
        "\n",
        "st.divider()\n",
        "\n",
        "# ==========================================================\n",
        "# 5️⃣ ANALISIS KORELASI\n",
        "# ==========================================================\n",
        "st.header(\"🔗 Heatmap Korelasi Antar Soal\")\n",
        "\n",
        "corr = indikator.corr()\n",
        "fig_corr, ax_corr = plt.subplots(figsize=(10, 8))\n",
        "fig_corr.patch.set_facecolor('#FFF0F5')\n",
        "\n",
        "sns.heatmap(corr, cmap=\"PiYG\", vmin=-1, vmax=1, ax=ax_corr,\n",
        "            cbar_kws={'label': 'Nilai Korelasi'}, linewidths=0.5, linecolor='white')\n",
        "\n",
        "ax_corr.set_title(\"Korelasi Pearson (Soal 1 - Soal 20)\", color='#9B89B3', fontweight='bold')\n",
        "ax_corr.tick_params(colors='#9B89B3')\n",
        "st.pyplot(fig_corr)\n",
        "\n",
        "st.divider()\n",
        "\n",
        "# ==========================================================\n",
        "# 6️⃣ ANALISIS REGRESI (Soal 1-19 terhadap Soal 20)\n",
        "# ==========================================================\n",
        "st.header(\"⚖️ Analisis Regresi Linear\")\n",
        "st.caption(\"Melihat pengaruh Soal_1 s/d Soal_19 terhadap hasil Soal_20\")\n",
        "\n",
        "X = sm.add_constant(indikator.iloc[:, 0:19])\n",
        "y = indikator.iloc[:, 19]\n",
        "\n",
        "model = sm.OLS(y, X, missing=\"drop\").fit()\n",
        "r2 = model.rsquared\n",
        "\n",
        "st.info(f\"📊 **Nilai R-Squared:** {r2:.3f} (Sejauh mana soal 1-19 menjelaskan variansi soal 20)\")\n",
        "\n",
        "coef = model.params[1:].sort_values(ascending=False).head(5)\n",
        "st.subheader(\"🔝 5 Faktor Paling Berpengaruh\")\n",
        "st.dataframe(coef.to_frame(\"Koefisien\"), use_container_width=True)\n",
        "\n",
        "st.divider()\n",
        "\n",
        "# ==========================================================\n",
        "# 7️⃣ SEGMENTASI SISWA (K-Means)\n",
        "# ==========================================================\n",
        "st.header(\"👥 Segmentasi Kemampuan Siswa\")\n",
        "\n",
        "scaler = StandardScaler()\n",
        "X_scaled = scaler.fit_transform(indikator.fillna(0))\n",
        "\n",
        "kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)\n",
        "cluster_label = kmeans.fit_predict(X_scaled)\n",
        "\n",
        "indikator_cluster = indikator.copy()\n",
        "indikator_cluster[\"Cluster\"] = cluster_label\n",
        "\n",
        "cluster_mean = indikator_cluster.groupby(\"Cluster\").mean()\n",
        "cluster_ranking = cluster_mean.mean(axis=1).sort_values(ascending=False).index\n",
        "\n",
        "segment_map = {\n",
        "    cluster_ranking[0]: \"🏆 Kelompok Mahir\",\n",
        "    cluster_ranking[1]: \"📈 Kelompok Menengah\",\n",
        "    cluster_ranking[2]: \"🌱 Kelompok Dasar\"\n",
        "}\n",
        "\n",
        "indikator_cluster[\"Segment\"] = indikator_cluster[\"Cluster\"].map(segment_map)\n",
        "\n",
        "def style_segment(val):\n",
        "    color = '#FFB3BA' if 'Dasar' in str(val) else '#FFDFBA' if 'Menengah' in str(val) else '#BAFFC9'\n",
        "    return f'background-color: {color}; color: #333;'\n",
        "\n",
        "styled_df = indikator_cluster[[\"Segment\"]].join(indikator).head(10).style.map(style_segment, subset=['Segment'])\n",
        "\n",
        "st.write(\"Hasil pengelompokan siswa (10 data teratas):\")\n",
        "st.dataframe(styled_df, use_container_width=True)\n",
        "\n",
        "st.success(\"✅ Dashboard siap digunakan.\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "oHYnL4dpX84x",
        "outputId": "be015a97-1fda-46e3-d93f-6f70303a9926"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Writing app_pastel.py\n"
          ]
        }
      ]
    }
  ]
}